services:
    web:
        image: fholzer/nginx-brotli:latest
        restart: unless-stopped
        ports:
            - "443:443"
            - "80:80"
        volumes:
            - .:/var/www:delegated
            - ./site.conf:/etc/nginx/conf.d/default.conf
            - ./cert.pem:/etc/nginx/cert.pem
            - ./cert.key:/etc/nginx/cert.key
        links:
            - php

    php:
        restart: unless-stopped
        build:
            context: docker/php
        volumes:
            - .:/var/www:delegated
        depends_on:
            - db

    db:
        restart: unless-stopped
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: dzeta
            TZ: Europe/Paris
        volumes:
            - db-data:/var/lib/mysql

    adminer:
        image: adminer
        restart: unless-stopped
        environment:
            APP_ENV: dev
            ADMINER_DESIGN: pepa-linha
            ADMINER_DEFAULT_SERVER: db
        ports:
            - "8888:8080"
        depends_on:
            - db
volumes:
    db-data:
        driver: local
